-- MySQL Script generated by MySQL Workbench
-- Sat Dec 24 12:33:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`AikidoTrainers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AikidoTrainers`;
CREATE TABLE IF NOT EXISTS `mydb`.`AikidoTrainers` (
  `ID` INT NOT NULL AUTO_INCREMENT UNIQUE,
  `Клуб` VARCHAR(128) NOT NULL,
  `ФИО` VARCHAR(128) CHARACTER SET 'utf8' NOT NULL,
  `Стиль` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`ФИО`)
)  
ENGINE = InnoDB;
CREATE INDEX `ID_INDEX` ON `AikidoTrainers` (`ID` ASC);

-- -----------------------------------------------------
-- Table `mydb`.`AikidoSportsmen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AikidoSportsmen`;
CREATE TABLE IF NOT EXISTS `mydb`.`AikidoSportsmen` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Клуб` VARCHAR(128) NOT NULL,
  `ФИО` VARCHAR(128) NOT NULL,
  `Стиль` VARCHAR(128) CHARACTER SET 'utf8' NOT NULL,
  `Тренер` VARCHAR(128) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `AikidoSportsmen_idx` (`Тренер` ASC) VISIBLE,
  CONSTRAINT `AikidoSportsmen`
    FOREIGN KEY (`Тренер`)
    REFERENCES `mydb`.`AikidoTrainers` (`ФИО`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`AikidoTrainers`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`AikidoTrainers` (`ID`,`Клуб`, `ФИО`, `Стиль`) VALUES (1, 'СК Волна', 'Брежнев Андрей Николаевич', 'Томики');
INSERT INTO `mydb`.`AikidoTrainers` (`ID`,`Клуб`, `ФИО`, `Стиль`) VALUES (2, 'СК Волна', 'Владимирова Екатерина Евгеньевна', 'Томики');
INSERT INTO `mydb`.`AikidoTrainers` (`ID`,`Клуб`, `ФИО`, `Стиль`) VALUES (3, 'СК Ленкай', 'Новиков Иван Анатольевич', 'Айкикай');
INSERT INTO `mydb`.`AikidoTrainers` (`ID`,`Клуб`, `ФИО`, `Стиль`) VALUES (4, 'СК Ленкай', 'Сапожников Дмитрий Сергеевич', 'Айкикай');
INSERT INTO `mydb`.`AikidoTrainers` (`ID`,`Клуб`, `ФИО`, `Стиль`) VALUES (5, 'СК Сейбукан', 'Беляев Михаил Григорьевич', 'Ёсинкан');
INSERT INTO `mydb`.`AikidoTrainers` (`ID`,`Клуб`, `ФИО`, `Стиль`) VALUES (6, 'СК Сейбукан', 'Малинин Андрей Владимирович', 'Ёсинкан');
INSERT INTO `mydb`.`AikidoTrainers` (`ID`,`Клуб`, `ФИО`, `Стиль`) VALUES (7 , 'СК Сейбукан', 'Беляева Мария Михайловна', 'Ёсинкан');
INSERT INTO `mydb`.`AikidoTrainers` (`ID`,`Клуб`, `ФИО`, `Стиль`) VALUES (8, 'СК Сейбукан', 'Шиманович Евгений Григорьевич', 'Ёсинкан');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`AikidoSportsmen`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`AikidoSportsmen` (`ID`, `Клуб`, `ФИО`, `Стиль`, `Тренер`) VALUES (1, 'СК Волна', 'Евсеева Виктория Денисовна', 'Томики', 'Брежнев Андрей Николаевич');
INSERT INTO `mydb`.`AikidoSportsmen` (`ID`, `Клуб`, `ФИО`, `Стиль`, `Тренер`) VALUES (2, 'СК Волна', 'Владимирова Екатерина Евгеньевна', 'Томики', 'Брежнев Андрей Николаевич');
INSERT INTO `mydb`.`AikidoSportsmen` (`ID`, `Клуб`, `ФИО`, `Стиль`, `Тренер`) VALUES (3, 'СК Ленкай', 'Рейх Елена Александровна', 'Айкикай', 'Сапожников Дмитрий Сергеевич');
INSERT INTO `mydb`.`AikidoSportsmen` (`ID`, `Клуб`, `ФИО`, `Стиль`, `Тренер`) VALUES (4 , 'СК Ленкай', 'Табачкова Виктория Дмитриевна', 'Айкикай', 'Новиков Иван Анатольевич');
INSERT INTO `mydb`.`AikidoSportsmen` (`ID`, `Клуб`, `ФИО`, `Стиль`, `Тренер`) VALUES (5, 'СК Сейбукан', 'Киселева Арина Борисовна', 'Ёсинкан', 'Беляева Мария Михайловна');
INSERT INTO `mydb`.`AikidoSportsmen` (`ID`, `Клуб`, `ФИО`, `Стиль`, `Тренер`) VALUES (6, 'СК Сейбукан', 'Алексеев Алексей Сергеевич', 'Ёсинкан', 'Малинин Андрей Владимирович');
INSERT INTO `mydb`.`AikidoSportsmen` (`ID`, `Клуб`, `ФИО`, `Стиль`, `Тренер`) VALUES (7, 'СК Сейбукан', 'Голицын Богдан Александрович', 'Ёсинкан', 'Шиманович Евгений Григорьевич');
INSERT INTO `mydb`.`AikidoSportsmen` (`ID`, `Клуб`, `ФИО`, `Стиль`, `Тренер`) VALUES (8, 'СК Сейбукан', 'Малинин Андрей Владимирович', 'Ёсинкан', 'Беляев Михаил Григорьевич');
INSERT INTO `mydb`.`AikidoSportsmen` (`ID`, `Клуб`, `ФИО`, `Стиль`, `Тренер`) VALUES (9, 'СК Сейбукан', 'Джуга Мария Викторовна', 'Ёсинкан', 'Малинин Андрей Владимирович');
INSERT INTO `mydb`.`AikidoSportsmen` (`ID`, `Клуб`, `ФИО`, `Стиль`, `Тренер`) VALUES (10, 'СК Волна', 'Пономарёва Светлана Николаевна', 'Томики', 'Брежнев Андрей Николаевич');

COMMIT;

